### ISSUE TITLE
add toc to content that previously had it

### ISSUE THREAD

**Issue by andreasbalevik** [Altinn/altinn-infoportal#14]
TOC is available in Netlify CMS as a shortcode. 

Previously content had a parameter `toc: true` front matter. Now the TOC has to be added in Netlify CMS.

- [ ] add TOC to content that previously had `toc:true`
- [ ] remove `toc:true` from the contents front-matter

**Comment by altinnadmin** [comment]
@andreasbalevik Why do we need to do this change? Doesn't Netlify support editing frontmatter parameters?
Using a parameter is simpler, shorter and doesn't "pollute" the markdown with shortcode-syntax.

**Comment by andreasbalevik** [comment]
Can add checkbox in Netlify to enable ToC or not.
