### ISSUE TITLE
Netlify CMS - add option to preview before publishing

### ISSUE THREAD

**Issue by andreasbalevik** [Altinn/altinn-infoportal#17]
Netlify CMS allows to preview the content before publishing. This works out of the box by adding this to the collection
```
    editor:
      preview: true
```
      
This shows the content as plain HTML without styling. To complete this task:

- [x] Research: add custom preview. [See netlify documentation](https://www.netlifycms.org/docs/customization/)
- [ ] #31

**Comment by andreasbalevik** [comment]
Preview of the markdown content will not work. You can style the content to match the webpage, but you would not get header, footer and other elements. 

The best way is to use preview links when using editorial workflow in Netlify CMS: https://github.com/netlify/netlify-cms/blob/master/website/content/blog/deploy-preview-links.md

Netlify CMS uses Github status API to get the preview URL. This works out of the box when hosting site on Netlify... (netlify builds site for each commit or PR and provide a preview url). In other words, when changing an article, a preview link is available in the CMS for the editor to visit and see changes like it would appear in production. 

Cant find a good solution for this using github actions.

**Comment by altinnadmin** [comment]
> deploy to Azure Static Web Apps, and that job returns a preview build URL

Sounds like this could be possible 👍 
https://docs.microsoft.com/en-us/azure/static-web-apps/review-publish-pull-requests#review-changes

**Comment by andreasbalevik** [comment]
Should be resolved in #2
